services:
  backend:
    build:
      context: ./core
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - quantaura-data:/app/data
      - ./core/private.pem:/app/private.pem:ro
      - ./core/public.pem:/app/public.pem:ro
    restart: always

  frontend:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  quantaura-data:
