//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use rust_decimal::Decimal;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "backtest_equity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub run_id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub ts: DateTimeWithTimeZone,
    pub equity: Decimal,
    pub available: Decimal,
    pub pnl: Decimal,
    pub pnl_pct: Decimal,
    pub dd_pct: Decimal,
    pub cycle: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
