//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "exchanges")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub exchange_type: String,
    #[sea_orm(column_type = "Text")]
    pub account_name: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    pub enabled: i32,
    #[sea_orm(column_type = "Text")]
    pub api_key: String,
    #[sea_orm(column_type = "Text")]
    pub secret_key: String,
    #[sea_orm(column_type = "Text")]
    pub passphrase: String,
    pub testnet: i32,
    #[sea_orm(column_type = "Text")]
    pub hyperliquid_wallet_addr: String,
    #[sea_orm(column_type = "Text")]
    pub aster_user: String,
    #[sea_orm(column_type = "Text")]
    pub aster_signer: String,
    #[sea_orm(column_type = "Text")]
    pub aster_private_key: String,
    #[sea_orm(column_type = "Text")]
    pub lighter_wallet_addr: String,
    #[sea_orm(column_type = "Text")]
    pub lighter_private_key: String,
    #[sea_orm(column_type = "Text")]
    pub lighter_api_key_private_key: String,
    pub lighter_api_key_index: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
