//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "runtime_alert_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub trader_id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    pub window_hours: i32,
    #[sea_orm(column_type = "Text")]
    pub thresholds_json: String,
    #[sea_orm(column_type = "Text")]
    pub rates_json: String,
    #[sea_orm(column_type = "Text")]
    pub alerts_json: String,
    pub breached: i32,
    #[sea_orm(column_type = "Text")]
    pub severity: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
