//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "runtime_alert_controls")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub trader_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub user_id: String,
    pub is_muted: i32,
    pub muted_until: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub mute_reason: String,
    pub acked_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub acked_by: String,
    #[sea_orm(column_type = "Text")]
    pub ack_note: String,
    pub updated_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
