//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "runtime_alert_delivery_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub trader_id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub alert_history_id: String,
    #[sea_orm(column_type = "Text")]
    pub destination: String,
    #[sea_orm(column_type = "Text")]
    pub endpoint: String,
    #[sea_orm(column_type = "Text")]
    pub request_headers_json: String,
    #[sea_orm(column_type = "Text")]
    pub request_body_json: String,
    pub response_status: i32,
    #[sea_orm(column_type = "Text")]
    pub response_body: String,
    pub attempt: i32,
    pub max_attempts: i32,
    pub success: i32,
    #[sea_orm(column_type = "Text")]
    pub error_message: String,
    pub latency_ms: i32,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
