//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use rust_decimal::Decimal;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "trader_orders")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub trader_id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub exchange_order_id: String,
    #[sea_orm(column_type = "Text")]
    pub client_order_id: String,
    #[sea_orm(column_type = "Text")]
    pub symbol: String,
    #[sea_orm(column_type = "Text")]
    pub side: String,
    #[sea_orm(column_type = "Text")]
    pub position_side: String,
    #[sea_orm(column_type = "Text")]
    pub order_type: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub price: Decimal,
    pub quantity: Decimal,
    pub filled_quantity: Decimal,
    pub avg_fill_price: Decimal,
    pub reduce_only: i32,
    #[sea_orm(column_type = "Text")]
    pub time_in_force: String,
    pub placed_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub closed_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
