//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use rust_decimal::Decimal;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "traders")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub ai_model_id: String,
    #[sea_orm(column_type = "Text")]
    pub exchange_id: String,
    #[sea_orm(column_type = "Text")]
    pub strategy_id: String,
    pub initial_balance: Decimal,
    pub scan_interval_minutes: i32,
    pub is_running: i32,
    pub is_cross_margin: i32,
    pub show_in_competition: i32,
    pub btc_eth_leverage: i32,
    pub altcoin_leverage: i32,
    #[sea_orm(column_type = "Text")]
    pub trading_symbols: String,
    pub use_ai500: i32,
    pub use_oi_top: i32,
    #[sea_orm(column_type = "Text")]
    pub custom_prompt: String,
    pub override_base_prompt: i32,
    #[sea_orm(column_type = "Text")]
    pub system_prompt_template: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
