use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(BacktestTrades::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(BacktestTrades::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(BacktestTrades::RunId).string().not_null())
                    .col(ColumnDef::new(BacktestTrades::UserId).string().not_null())
                    .col(
                        ColumnDef::new(BacktestTrades::Ts)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(BacktestTrades::Symbol).string().not_null())
                    .col(ColumnDef::new(BacktestTrades::Action).string().not_null())
                    .col(
                        ColumnDef::new(BacktestTrades::Side)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(BacktestTrades::Qty)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BacktestTrades::Price)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BacktestTrades::Fee)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BacktestTrades::Slippage)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BacktestTrades::OrderValue)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BacktestTrades::RealizedPnl)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BacktestTrades::Leverage)
                            .integer()
                            .not_null()
                            .default(1),
                    )
                    .col(
                        ColumnDef::new(BacktestTrades::Cycle)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BacktestTrades::PositionAfter)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BacktestTrades::Liquidation)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BacktestTrades::Note)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_backtest_trades_run_ts")
                    .table(BacktestTrades::Table)
                    .col(BacktestTrades::RunId)
                    .col((BacktestTrades::Ts, IndexOrder::Asc))
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .if_exists()
                    .table(BacktestTrades::Table)
                    .to_owned(),
            )
            .await
    }
}

#[derive(DeriveIden)]
enum BacktestTrades {
    Table,
    Id,
    RunId,
    UserId,
    Ts,
    Symbol,
    Action,
    Side,
    Qty,
    Price,
    Fee,
    Slippage,
    OrderValue,
    RealizedPnl,
    Leverage,
    Cycle,
    PositionAfter,
    Liquidation,
    Note,
}
