use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(RuntimeAlertDeliveryLog::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(RuntimeAlertDeliveryLog::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(RuntimeAlertDeliveryLog::TraderId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RuntimeAlertDeliveryLog::UserId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RuntimeAlertDeliveryLog::AlertHistoryId)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(RuntimeAlertDeliveryLog::Destination)
                            .string()
                            .not_null()
                            .default("webhook"),
                    )
                    .col(
                        ColumnDef::new(RuntimeAlertDeliveryLog::Endpoint)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(RuntimeAlertDeliveryLog::RequestHeadersJson)
                            .string()
                            .not_null()
                            .default("{}"),
                    )
                    .col(
                        ColumnDef::new(RuntimeAlertDeliveryLog::RequestBodyJson)
                            .string()
                            .not_null()
                            .default("{}"),
                    )
                    .col(
                        ColumnDef::new(RuntimeAlertDeliveryLog::ResponseStatus)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(RuntimeAlertDeliveryLog::ResponseBody)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(RuntimeAlertDeliveryLog::Attempt)
                            .integer()
                            .not_null()
                            .default(1),
                    )
                    .col(
                        ColumnDef::new(RuntimeAlertDeliveryLog::MaxAttempts)
                            .integer()
                            .not_null()
                            .default(1),
                    )
                    .col(
                        ColumnDef::new(RuntimeAlertDeliveryLog::Success)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(RuntimeAlertDeliveryLog::ErrorMessage)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(RuntimeAlertDeliveryLog::LatencyMs)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(RuntimeAlertDeliveryLog::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_runtime_alert_delivery_log_trader_created")
                    .table(RuntimeAlertDeliveryLog::Table)
                    .col(RuntimeAlertDeliveryLog::TraderId)
                    .col((RuntimeAlertDeliveryLog::CreatedAt, IndexOrder::Desc))
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_runtime_alert_delivery_log_user_created")
                    .table(RuntimeAlertDeliveryLog::Table)
                    .col(RuntimeAlertDeliveryLog::UserId)
                    .col((RuntimeAlertDeliveryLog::CreatedAt, IndexOrder::Desc))
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_runtime_alert_delivery_log_success_created")
                    .table(RuntimeAlertDeliveryLog::Table)
                    .col(RuntimeAlertDeliveryLog::Success)
                    .col((RuntimeAlertDeliveryLog::CreatedAt, IndexOrder::Desc))
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_runtime_alert_delivery_log_alert_history")
                    .table(RuntimeAlertDeliveryLog::Table)
                    .col(RuntimeAlertDeliveryLog::AlertHistoryId)
                    .col((RuntimeAlertDeliveryLog::CreatedAt, IndexOrder::Desc))
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .if_exists()
                    .table(RuntimeAlertDeliveryLog::Table)
                    .to_owned(),
            )
            .await
    }
}

#[derive(DeriveIden)]
enum RuntimeAlertDeliveryLog {
    Table,
    Id,
    TraderId,
    UserId,
    AlertHistoryId,
    Destination,
    Endpoint,
    RequestHeadersJson,
    RequestBodyJson,
    ResponseStatus,
    ResponseBody,
    Attempt,
    MaxAttempts,
    Success,
    ErrorMessage,
    LatencyMs,
    CreatedAt,
}
