use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Exchanges::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Exchanges::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Exchanges::ExchangeType)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Exchanges::AccountName)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .col(ColumnDef::new(Exchanges::UserId).string().not_null())
                    .col(ColumnDef::new(Exchanges::Name).string().not_null())
                    .col(
                        ColumnDef::new(Exchanges::Type)
                            .string()
                            .not_null()
                            .default("cex"),
                    )
                    .col(
                        ColumnDef::new(Exchanges::Enabled)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(Exchanges::ApiKey)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Exchanges::SecretKey)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Exchanges::Passphrase)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Exchanges::Testnet)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(Exchanges::HyperliquidWalletAddr)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(Exchanges::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Exchanges::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_exchanges_user_id")
                    .table(Exchanges::Table)
                    .col(Exchanges::UserId)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_exchanges_user_type")
                    .table(Exchanges::Table)
                    .col(Exchanges::UserId)
                    .col(Exchanges::ExchangeType)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_exchanges_user_type_account")
                    .table(Exchanges::Table)
                    .col(Exchanges::UserId)
                    .col(Exchanges::ExchangeType)
                    .col(Exchanges::AccountName)
                    .unique()
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().if_exists().table(Exchanges::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum Exchanges {
    Table,
    Id,
    ExchangeType,
    AccountName,
    UserId,
    Name,
    Type,
    Enabled,
    ApiKey,
    SecretKey,
    Passphrase,
    Testnet,
    HyperliquidWalletAddr,
    CreatedAt,
    UpdatedAt,
}
